### PR TITLE
#84: Fixed the cell-span processing

### PR DESCRIPTION
**Pull request by DunaMariusCosmin**
Fixed the cell-span processing (#84)

### CODE REVIEW

**Comment by raducoravu** [comment]
The fix is both for Markdown-style tables with spans and for HTML style tables containing spans and used inside Markdown.

**Comment by kirkilj** [comment]
Are the text alignment options in Multimarkdown supported or just the spanning?

**Comment by DunaMariusCosmin** [comment]
My pull request fixes only the spanning.
But I created this sample that contains text alignment option in markdown table and text alignment in HTML table:
[sample.md](https://github.com/jelovirt/org.lwdita/files/8243371/sample.md)
And the "align" attributes were corrected added to the DITA output.

Can you give us an example where the text alignment processing doesn't work as you expected?

**Comment by kirkilj** [comment]
I don't have an example of it not working. I was just asking in general about other Multimarkdown table features. Thanks.

**Comment by thendarion** [comment]
so why was cell spanning disabled originally in org.lwdita?

**Comment by jelovirt** [comment]
The code has been merged with some changes in #94.

**Pull request closed without merging**
